# Generated by Django 4.2.23 on 2025-09-01 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resume.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Resume', max_length=255, verbose_name='title')),
                ('template_type', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal')], default='classic', max_length=20, verbose_name='template type')),
                ('data_json', models.JSONField(help_text='Structured data for the resume content (personal info, education, experience, etc.)', verbose_name='resume data JSON')),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to=resume.models.resume_pdf_upload_path, verbose_name='generated PDF')),
                ('shareable_link_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='shareable link token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-created_at'],
            },
        ),
    ]
