# Generated by Django 4.2.23 on 2025-09-01 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('company', models.CharField(max_length=255, verbose_name='company')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('description', models.TextField(verbose_name='description')),
                ('requirements', models.TextField(blank=True, verbose_name='requirements')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='external URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='posted at')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to=settings.AUTH_USER_MODEL, verbose_name='posted by')),
            ],
            options={
                'verbose_name': 'Job Opening',
                'verbose_name_plural': 'Job Openings',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('resource_type', models.CharField(choices=[('law', 'Law'), ('advice', 'Advice'), ('template', 'Template'), ('funding', 'Funding'), ('training', 'Training')], max_length=20, verbose_name='resource type')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_resources_added', to=settings.AUTH_USER_MODEL, verbose_name='added by')),
            ],
            options={
                'verbose_name': 'Business Resource',
                'verbose_name_plural': 'Business Resources',
                'ordering': ['-created_at'],
            },
        ),
    ]
