# Generated by Django 4.2.23 on 2025-09-01 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('json_filename', models.CharField(help_text="Name of the JSON file containing assessment data (e.g., 'holland.json')", max_length=255, verbose_name='JSON filename')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='price')),
                ('min_age', models.PositiveIntegerField(help_text='Minimum age to access this package', verbose_name='minimum age')),
                ('max_age', models.PositiveIntegerField(help_text='Maximum age to access this package', verbose_name='maximum age')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Test Package',
                'verbose_name_plural': 'Test Packages',
                'ordering': ['min_age', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserAssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is completed')),
                ('raw_results_json', models.JSONField(blank=True, help_text='Raw user answers and initial scoring results.', null=True, verbose_name='raw results JSON')),
                ('deepseek_input_json', models.JSONField(blank=True, help_text='Processed data ready to be sent to the AI service.', null=True, verbose_name='deepseek input JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='assessment.assessment', verbose_name='assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Assessment Attempt',
                'verbose_name_plural': 'User Assessment Attempts',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='assessment.testpackage', verbose_name='package'),
        ),
    ]
