# Generated by Django 4.2.23 on 2025-09-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='package',
        ),
        migrations.AddField(
            model_name='assessment',
            name='packages',
            field=models.ManyToManyField(blank=True, help_text='The test packages this assessment belongs to.', related_name='assessments', to='assessment.testpackage', verbose_name='packages'),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Price of the package in Iranian Rials.', max_digits=15, verbose_name='price (Rials)'),
        ),
    ]
