# Generated by Django 4.2.23 on 2025-09-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_remove_assessment_package_assessment_packages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='packages',
        ),
        migrations.AddField(
            model_name='testpackage',
            name='assessments',
            field=models.ManyToManyField(blank=True, help_text='The assessments included in this package.', related_name='packages', to='assessment.assessment', verbose_name='assessments'),
        ),
    ]
