# Generated by Django 4.2.24 on 2025-09-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_remove_assessment_packages_testpackage_assessments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpackage',
            name='assessments',
        ),
        migrations.AddField(
            model_name='assessment',
            name='packages',
            field=models.ManyToManyField(blank=True, help_text='The test packages this assessment belongs to.', related_name='assessments', to='assessment.testpackage', verbose_name='packages'),
        ),
    ]
