# Generated by Django 4.2.23 on 2025-09-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_remove_assessment_packages_testpackage_assessments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userassessmentattempt',
            name='deepseek_input_json',
        ),
        migrations.AddField(
            model_name='userassessmentattempt',
            name='processed_results_json',
            field=models.JSONField(blank=True, help_text='Processed/calculated data derived from raw results, ready for AI service.', null=True, verbose_name='processed results JSON'),
        ),
        migrations.AlterField(
            model_name='userassessmentattempt',
            name='raw_results_json',
            field=models.JSONField(blank=True, help_text='Raw user answers and initial scoring results, updated incrementally.', null=True, verbose_name='raw results JSON'),
        ),
    ]
