# Generated by Django 4.2.26 on 2025-11-10 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessment",
            "0006_remove_userassessmentattempt_deepseek_input_json_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_integration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A user-friendly name for the AI provider (e.g., 'Ollama Cloud').",
                        max_length=100,
                        verbose_name="provider name",
                    ),
                ),
                (
                    "settings_config_key",
                    models.CharField(
                        help_text="The key that matches a provider's configuration in the `AI_PROVIDERS` dictionary in settings.",
                        max_length=50,
                        unique=True,
                        verbose_name="settings config key",
                    ),
                ),
                (
                    "is_active_for_users",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, this provider will be available for users to select.",
                        verbose_name="active for users",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "AI Provider",
                "verbose_name_plural": "AI Providers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AIInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "full_request",
                    models.JSONField(
                        help_text="The complete request payload sent to the AI provider.",
                        verbose_name="full request",
                    ),
                ),
                (
                    "full_response",
                    models.JSONField(
                        blank=True,
                        help_text="The complete, raw response from the AI provider.",
                        null=True,
                        verbose_name="full response",
                    ),
                ),
                (
                    "processed_response",
                    models.TextField(
                        blank=True,
                        help_text="The clean, user-facing text extracted from the full response.",
                        verbose_name="processed response",
                    ),
                ),
                (
                    "http_status_code",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The HTTP status code of the response from the AI provider.",
                        null=True,
                        verbose_name="http status code",
                    ),
                ),
                (
                    "timestamp_sent",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="timestamp sent"
                    ),
                ),
                (
                    "timestamp_received",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="timestamp received"
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_interactions",
                        to="assessment.testpackage",
                        verbose_name="package",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interactions",
                        to="ai_integration.aiprovider",
                        verbose_name="provider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_interactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Interaction",
                "verbose_name_plural": "AI Interactions",
                "ordering": ["-timestamp_sent"],
                "unique_together": {("user", "package")},
            },
        ),
    ]
